### ISSUE TITLE
[BUG] README shows NPM install. Package is not in NPM yet

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/opensearch-js#168]
**What is the bug?**

The README says you can run:
```
npm install @opensearch/opensearch
```

This yields: ` '@opensearch/opensearch@*' is not in the npm registry.`

While this is likely a temporary problem those stumbling upon the repo shouldn't be lead astray.

**What is the expected behavior?**
The README should not list `npm install` if the package isn't (yet) in the registry.

**Do you have any screenshots?**
<img width="562" alt="Screen Shot 2021-08-31 at 10 12 54 AM" src="https://user-images.githubusercontent.com/1152927/131538624-cfa27867-7da7-4237-b9c8-58076ef4ec79.png">

**Comment by oliversalzburg** [comment]
May I ask why the package isn't being published? Consuming packages from git is less than ideal.

**Comment by stockholmux** [comment]
@oliversalzburg It's in process. It'll be in NPM soon.
