### ISSUE TITLE
[FEATURE] SAML authentication

### ISSUE THREAD

**Issue by clenkiu** [opensearch-project/opensearch-js#186]
The OpenSearch JavaScript client only supports basic authentication on its implementation.
It is not possible to use the library authenticating users with SSO, using SAML authentication.

This is, by example, implemented in the ElasticSearch nodejs client version 7.14 and above, as described here:.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_security_samlprepareauthentication
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_security_samlauthenticate

I would like to have a similar implementation in the OpenSearch JavaScript client.

**Comment by clenkiu** [comment]
Is there any plan to implement this enhancement request?

**Comment by dblock** [comment]
Would be great to have this, please do contribute! 

Please do note that we cannot be copying code from non-APLv2 licensed sources, always confirm that you have not copied any such thing.

**Comment by wbeckler** [comment]
The SAML implementation of the OpenSearch security plugin, as far as I can tell from the [docs](https://opensearch.org/docs/latest/security-plugin/configuration/saml/), does not support backend authentication. It only does browser-based. Therefore this feature would not work on the node.js client.

I will close this unless there are objections. If you need the feature, please request it here: https://github.com/opensearch-project/security/issues/new?assignees=&labels=enhancement%2C+untriaged&template=feature_request.md&title=%5BFEATURE%5D
