### ISSUE TITLE
[FEATURE] Support the scroll API

### ISSUE THREAD

**Issue by jsinai** [opensearch-project/opensearch-js#188]
It would be convenient if the JavaScript client supports the Scroll API, similar to the Elastic client:

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_scroll

At present, we have to use separate code for API calls not supported by the client.

**Comment by nhtruong** [comment]
Closing this. 
@jsinai If the healper feature mentioned about does not fulfill your need, feel free to create a new issue or reopen this one. Thank you.
