### ISSUE TITLE
Redirect types in package.json to api/new.d.ts

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-js#204]
Currently, in package.json, types is still using index.d.ts. 
```
"name": "@opensearch-project/opensearch",
  "description": "The official OpenSearch client for Node.js",
  "main": "index.js",
  "types": "index.d.ts",
  "exports": {
    ".": {
      "require": "./index.js",
      "import": "./index.mjs"
    },
    "./": "./"
  },

...
```
However, the api types have been updated and the new types are api/new.d.ts. Therefore, we need either change `types` in package.json or copy api/new.d.ts to index.d.ts

**Comment by elimumford** [comment]
This issue get's even worse with TS 4.7+ and ESM as it only supports the `exports` tree when present. 

Simply adding `types` to the `exports` tree solves a lot of issues... and will not break anything.  2.0.1 please...

```json
...
 "exports": {
    ".": {
      "require": "./index.js",
      "import": "./index.mjs",
      "types": "./api/new.d.ts"
    },
    "./": "./"  
  },
...
```
> Note the ` "./": "./"` is not a valid export either... 

I've written post install scripts to monkey patch the package.json in my node_modules so I can keep my sanity.

**Comment by wbeckler** [comment]
This makes sense. Would you be willing to draft a PR?

**Comment by Tomas2D** [comment]
+1

**Comment by e10jc** [comment]
Just wanted to share this, in case anyone wants to use it:
```
"postinstall": "sed -i '' 's/index\\.d\\.ts/\\.\\/api\\/new\\.d\\.ts/' node_modules/@opensearch-project/opensearch/package.json"
```

**Comment by dblock** [comment]
@e10jc Care to PR a fix here?

**Comment by GTRanger** [comment]
Is there a reason why this hasn't been picked up after a year of being open? Assuming the proposal is as simple as the requestor says, this should be a trivial change that would vastly improve the Typescript development experience. If the request is not so simple, it would be nice to know why this is the case.

**Comment by GTRanger** [comment]
Is there an ETA for when this will be picked up? It seems like a relatively straightforward fix that would vastly improve the Typescript development experience.

**Comment by wbeckler** [comment]
If you have a fix, feel free to PR it

**Comment by GTRanger** [comment]
Is there something that I am missing here that makes this more complicated than just replacing the types in the `package.json` file? I am skeptical that the package maintainers would leave this issue open for over a year if the fix were so simple. What's the catch that isn't immediately obvious to those of us who haven't worked on this package before?

**Comment by dblock** [comment]
@GTRanger Package maintainers forked existing code from ES, and don't know better than you. It may be as simple. At a first look all the changes in new/types precede the fork, and I have no idea why we have both `types` and `new`, for example. Appreciate any help you can provide.

**Comment by kavilla** [comment]
> @GTRanger Package maintainers forked existing code from ES, and don't know better than you. It may be as simple. At a first look all the changes in new/types precede the fork, and I have no idea why we have both `types` and `new`, for example. Appreciate any help you can provide. 

We had to keep both for OpenSearch Dashboards because the `new` led to breaking changes when forking. Package consumers can choose to use the new but existing code most likely referenced the old. We have cam change to use the new API types in our repo but we should consider other users of package when changing over.
