### ISSUE TITLE
[BUG] Program terminates when the status code in the response to an API request is 429.

### ISSUE THREAD

**Issue by huuyafwww** [opensearch-project/opensearch-js#231]
**What is the bug?**
Exit when an error occurs in the response to an API request.

**How can one reproduce the bug?**
When OpenSearch is under heavy load, make search and bulk requests and have them respond with a 429 error.

**What is the expected behavior?**
Escalate errors to programs that use this library without terminating the program.
The reason is that [retries](https://github.com/opensearch-project/opensearch-js/blob/main/lib/Helpers.js#L728) do not work in helpers.bulk.

Therefore, when a 429 error occurs in the first place, it is terminated before reaching [this part](https://github.com/opensearch-project/opensearch-js/blob/main/lib/Helpers.js#L705).

**What is your host/environment?**
- OS: MacOS 12.2.1(intel chip
- Version: opensearch-js 1.1.0

**Do you have any additional context?**

This is the error I have identified.

```
node_modules/@opensearch-project/opensearch/lib/Transport.js:374
const error = new ResponseError(result)
ResponseError: Response Error
at onBody (node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)
at IncomingMessage.onEnd (node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)
at IncomingMessage.emit (node:events:539:35)
at endReadableNT (node:internal/streams/readable:1345:12
at processTicksAndRejections (node:internal/process/task_queues:83:21) 
```

**Comment by huuyafwww** [comment]
I'm sorry.
It was my lack of confirmation.
I was verifying client.bulk, not client.helpers.bulk.

**Comment by jeff-pal** [comment]
Hi @huuyafwww can you pls clarify the reason of that error?
