### ISSUE TITLE
Release version 2.0.0 for JS client

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-js#245]
Release the client version 2.0.0. Before releasing, the following items need to be done:

- [x] Add OpenSearch 2.0 to the integration [test matrix](https://github.com/opensearch-project/opensearch-js/blob/main/.github/workflows/compatibility.yml#L12).
- [x] Bump the client version to 2.0.0.
- [x] Cut a 2.0 branch for the client.

**Comment by ananzh** [comment]
get 2.0.0 published.
close this issue.
