### ISSUE TITLE
Which API is used for update a document in nodejs?

### ISSUE THREAD

**Issue by zhaoyi0113** [opensearch-project/opensearch-js#251]
I am using `.index` method to insert a document to index. But I can't find which method can be used to update an existing document. 
I can only find a REST API in opensearch document but where I can find the document about this nodejs library.

```
opensearchClient.index({
    id,
    index: indexName,
    body: t,
  });
```

**Comment by dcyprianrw** [comment]
This should be in the main documentation!  I had to search issues to find it. Thanks for posting @zhaoyi0113

**Comment by dblock** [comment]
@dcyprianrw Care to open an issue in https://github.com/opensearch-project/documentation-website or here?

**Comment by dcyprianrw** [comment]
@dblock I'm inexperienced at contributing here.   By opening an issue, do you mean pairing it with a PR to update the documentation as well?  I would be doing all those steps for the first time.

**Comment by dblock** [comment]
If you want to update the doc, you'll be my hero. But at the very least do open an issue so we don't forget to fix this (whether you fix it yourself or not). Does this help?

**Comment by dcyprianrw** [comment]
@dblock Ok, I opened issue 902 as shown above.  Probably safer for a newb like me to open an issue than offer a PR.  Hope this helps, thanks!
