### ISSUE TITLE
[FEATURE] How can I create an index with mapping

### ISSUE THREAD

**Issue by zhaoyi0113** [opensearch-project/opensearch-js#260]
I get this code from the readme about creating an index with settings. But I can't find how I can create the index with a predefined fields mapping. Is it supported by this lib?

```
var settings = {
    settings: {
      index: {
        number_of_shards: 4,
        number_of_replicas: 3,
      },
    },
  };

  var response = await client.indices.create({
    index: index_name,
    body: settings,
  });
```

**Comment by coolb0y** [comment]
@zhaoyi0113 Hey did you found the answer how to do mapping . I want to make only few fields searchable and other fields as filterable and aggregate fields. Any one know how to do this?

**Comment by wbeckler** [comment]
There's a user guide by @Nicksqain on how to do this: https://github.com/opensearch-project/opensearch-js/blob/main/guides/index_lifecycle.md
