### ISSUE TITLE
[BUG] Can't use ResponseError

### ISSUE THREAD

**Issue by DKurilo** [opensearch-project/opensearch-js#267]
### What is the bug?
OpenSearch throws `ResponseError` that is here:
```
import { ResponseError } from '@opensearch-project/opensearch/lib/errors';
```
and check like: `e instanceof ResponseError` throws:
```
Error: Package subpath './lib/errors' is not defined by "exports" in .../node_modules/@opensearch-project/opensearch/package.json
```

### How can one reproduce the bug?
1. start new OpenSearch server (at least server with no ingest pipelnes) locally
2. use code like:
```
import { Client } from '@opensearch-project/opensearch';
import { ResponseError } from '@opensearch-project/opensearch/lib/errors';

const client = new Client({ node: 'http://localhost:9200' });
try {
  const pipelinesResp = await this.client.ingest.getPipeline();
} catch (e) {
  if (e instanceof ResponseError && e.meta.statusCode === 404) {
    return [];
  }
}
```
3. when no pipelines OpenSearch returns 404 with `{}` as body and it makes client throw `ResponseError` and to catch it I need to parse it instead of just using `instanceof`.

### What is the expected behavior?
`ResponseError` is exported in index.d.ts or `./lib/errors` added to `exports` section of package.json.

### What is your host/environment?
MacOS, latest. But it's not important.

### Do you have any screenshots?
No

### Do you have any additional context?
I hope I described everything.

**Comment by AMoo-Miki** [comment]
What things work if you do this?
```
import { Client, errors: { ResponseError } } from '@opensearch-project/opensearch';
```

**Comment by DKurilo** [comment]
@AMoo-Miki , it works! Thank you.
For some reason I didn't notice
```
import * as errors from './lib/errors';
```
in `index.d.ts`
We can close this ticket.

**Comment by ckifer** [comment]
Commenting on this as I'm having issues importing `errors` like this in Jest tests. Everything is undefined `const { ResponseError } = errors;` throws 

```
 TypeError: Cannot destructure property 'ResponseError' of '((cov_s37s69r0l(...).s[11]++) , opensearch_2.errors)' as it is undefined.
```
