### ISSUE TITLE
[FEATURE] support upsert api

### ISSUE THREAD

**Issue by zhaoyi0113** [opensearch-project/opensearch-js#273]
I am using `client.index{document}` to insert a new document on the index and use `update` API to update an existing document. Is there an API for `upsert` a document? like insert if not exist otherwise update.

**Comment by dblock** [comment]
In ES this is just an [update](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docs-update.html#upserts). I would confirm that this works with OpenSearch and open a documentation issue to clarify in the OpenSearch docs.

**Comment by StefanSafeguard** [comment]
It's obscure to find in the OpenSearch documentation however it is referenced on this page https://opensearch.org/docs/1.2/opensearch/index-data/ in the update section. Easiest is to ctrl+f and search for upsert on this page.

**Comment by dblock** [comment]
@StefanSafeguard How do I do it from the JS client?

**Comment by StefanSafeguard** [comment]
You should be able to provide a object in the `body` parameter of the params argument thats structured as followed on the `update` method of the client.

```
{
  "doc": {
     ... fields to update
  },
 "upsert": {
    ... fields to create new document with
 }
}
```

I do have to say I haven't tested this directly on the `update` call, but I use the structure above within a `bulk` call and it works like a charm.

**Comment by dblock** [comment]
@zhaoyi0113 I think we can close this, but feel free to reopen/comment/suggest how we can improve any of it.

**Comment by zhaoyi0113** [comment]
I see there is a HTTP api for that but I can't make the nodejs client library work: `@opensearch-project/opensearch`.

**Comment by dblock** [comment]
@zhaoyi0113 What have you tried?
