### ISSUE TITLE
[FEATURE] Default getCredentials for AWS Sigv4 Signer

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-js#290]
### Is your feature request related to a problem?

In https://github.com/opensearch-project/opensearch-js/pull/279 we introduced Sigv4 signing. To use this one must decide which version of AWS SDK to import, then implement different ways to get credentials depending on the version.

### What solution would you like?

A version-agonostic default implementation. I want to be able to write the following regardless of the version of AWS SDK I am importing and without having to include any boilerplate for getting/refreshing credentials. And I want it to "just work" (TM) when I set, for example, credentials via ENV AWS_ variables.

```js
const client = new Client({
  ...AwsSigv4Signer({
      region: 'us-east-1',
      node: "https://search-xxx.region.es.amazonaws.com",
  })
});
```

(this is similar to how one can use a client in the [Java SDK](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html#request-signing-java)).

**Comment by Kyeong1024** [comment]
you guys make @opensearch-project/opensearch/aws theseday. But when I install module lik this `npm i @opensearch-project/opensearch`.  
I CANNOT find aws folder at node_modules. please fix this issue.
thank you.

**Comment by wbeckler** [comment]
@Kyeong1024 Can you start a new issue with your request? (https://github.com/opensearch-project/opensearch-js/issues/new/choose)
