### ISSUE TITLE
[FEATURE] Standardize, setup, report, and increase test coverage

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-js#298]
Setup code coverage, once reporting from CI/CD analyze the test gap and fill it.

See the meta issue https://github.com/opensearch-project/opensearch-clients/issues/30 for details.

**Comment by dblock** [comment]
No preference on coverage tool.

**Comment by DiyazY** [comment]
@dblock Thank you! I will take this issue.
