### ISSUE TITLE
[BUG]  ConfigurationError: Missing required parameter: body

### ISSUE THREAD

**Issue by innoneo-rahulkrishnan** [opensearch-project/opensearch-js#300]
### What is the bug?
I am getting an error `ConfigurationError: Missing required parameter: body` when trying to add a document to an index.

### How can one reproduce the bug?
I am trying to index a mongodb document.

`{
  clientId: [ { linkedIn: 'abcd' } ],
  loginType: [ 'efgh' ],
  status: 'logged_in',
  isSecurePassword: true,
  isMock: false,
  isCreatedByAdmin: false,
  firstName: 'Rahul',
  lastName: 'Krishnan',
  linkedInImageURL: ',
  emailId: 'rahul@haspaces.com',
  roleId: '630c8f42d0d76e39ecea5c59',
  createdAt: 2022-09-01T10:30:59.950Z,
  updatedAt: 2022-09-26T10:42:19.475Z,
  candidateId: 50,
  __v: 0,
  alternateEmailId: 'cmcturland@email.com',
  alternatePhoneNumber: { value: '', country: 'in', dialCode: '' },
  phoneNumber: { value: '234234234234', country: 'in', dialCode: '91' },
  middleName: null
}`
My code to index the document:
`    await client.index({
      id,
      index: 'candidates',
      body: data || {},
      refresh: true
    })`
    
  While doing this I am getting an error as shown in the image below.

### What is your host/environment?
macOs Menterey, 12.5.1

node version -> 16.17.0
npm version -> 8.15.0

### Do you have any screenshots?
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/76936119/192461121-0a3de218-3cfe-43f3-b3c9-7fa6245420bc.png">

**Comment by dblock** [comment]
@innoneo-rahulkrishnan What was your fix?
