### ISSUE TITLE
[FEATURE] Alllow overriding the aws service identifier in AwsSigv4Signer 

### ISSUE THREAD

**Issue by bwg** [opensearch-project/opensearch-js#330]
### Is your feature request related to a problem?
Currently the service identifier is hard coded to `es` with no way to override.

https://github.com/opensearch-project/opensearch-js/blob/2.1/lib/aws/AwsSigv4Signer.js#L73

### What solution would you like?
Allow overriding the default with a user provided value from opts
```
request.service = opts.service || 'es';
```

### What alternatives have you considered?
rolling our own signing functionality

**Comment by wbeckler** [comment]
This makes sense. Feel free to contribute a PR.

**Comment by dblock** [comment]
Closing via https://github.com/opensearch-project/opensearch-js/pull/333
