### ISSUE TITLE
I can't escape special characters

### ISSUE THREAD

**Issue by auriga1** [opensearch-project/opensearch-js#331]
Hi everyone,
I can't understand how to escape dash when I send the query to opensearch.
I'm using this structure to search on every field in my index:

```
{
    "index": "preg",
    "body": {
        "query": {
            "bool": {
                "must": [
                    {
                        "query_string": {
                            "query": "*2022*"
                        }
                    },
                    {
                        "bool": {
                            "should": [
                                {
                                    "match": {
                                        "owner": 6
                                    }
                                },
                                {
                                    "match": {
                                        "owner": 2
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
}
```

and everything works fine.
But when I add a dash to the date (2022-), no items are found.
I tried with "2022\\-" but it still doesn't work.

Can you tell me what is the correct way to escape special chars?

**Comment by wbeckler** [comment]
I think the best place for a question like this would be the OpenSearch forum: https://forum.opensearch.org/
If you post here, you'll target the js topic area: https://forum.opensearch.org/tags/c/clients/60/opensearch-js

**Comment by auriga1** [comment]
you're right, sorry.
