### ISSUE TITLE
[BUG] incomplete typing for `SearchRequest.sort`

### ISSUE THREAD

**Issue by leonardbinet** [opensearch-project/opensearch-js#338]
### What is the bug?
Wrong typing for `sort` options of `SearchRequest` `api/types.d.ts`: https://github.com/opensearch-project/opensearch-js/blob/main/api/types.d.ts#L959

The library type is:
```
sort?: string | string[];
```

Whereas actual type is broader: cf https://opensearch.org/docs/2.4/opensearch/search/sort/
example in documentation is: 
```
"sort": [
    {
      "line_id": {
        "order": "desc"
      }
    }
```

Note for inspiration: elasticsearch-js types: https://github.com/elastic/elasticsearch-js/blob/main/src/api/types.ts#L2377

**Comment by nhtruong** [comment]
Hi @leonardbinet. I believe the [sort param](https://github.com/opensearch-project/opensearch-js/blob/main/api/types.d.ts#L959) you're referring to is a [URL parameter](https://opensearch.org/docs/2.4/api-reference/search/#url-parameters) which is "_A comma-separated list of <field> : <direction> pairs to sort by._". So, `string | string[]` type is appropriate.


The other `sort` is actually a part of the `body` parameter, which is defined here:
https://github.com/opensearch-project/opensearch-js/blob/871a6669c9153d8161b3bbbce8747b86f9e6f758/api/types.d.ts#L979

**Comment by leonardbinet** [comment]
my bad, indeed!
