### ISSUE TITLE
[BUG] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package 

### ISSUE THREAD

**Issue by mustafawafa** [opensearch-project/opensearch-js#343]
### What is the bug?
I got this deprecation warning when using the package inside lambada ( runtime node v16)

`DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package `

### How can one reproduce the bug?
- use lambada runtime node v16 
- install the opensearch package 
- run the lambada 

### What is the expected behavior?
no warnings

### What is your host/environment?
- lambada runtime node v16

### Do you have any screenshots?
![Screenshot 2022-12-08 at 15 47 48](https://user-images.githubusercontent.com/56306428/206476919-a9731208-b83d-4d55-b2df-66a7b9fc1ea6.png)

### Do you have any additional context?
this can be fixed by change the mapping of "exports" inside [package.json ](https://github.com/opensearch-project/opensearch-js/blob/2f840e54860419f76ef8354a0fe070403d437386/package.json#L13)

**Comment by wbeckler** [comment]
Feel free to submit a PR for this.

**Comment by hardins01** [comment]
@mustafawafa Do you plan on making a PR to fix this?
