### ISSUE TITLE
[BUG] ignore apostrophes in elasticsearch

### ISSUE THREAD

**Issue by ahmadedris0** [opensearch-project/opensearch-js#357]
I am using nodejs with nestjs framework and I am getting data from opensearch but I want to ignore the apostrophes.

For example I have Mcdonald's as name in the opensearch and I want to send query donalds or mcdonalds and I want to get all records has Mcdonald's as name

Example for my code:

```
openSearch.search({
      index: IndexType,
      body: {
        size: 1000,
        query: {
          bool: {
            should: [
              {
                match: {
                  name: {
                    query: name,
                    fuzziness: 0,
                    boost: 10,
                  },
                },
              },
              {
                match: {
                  name: {
                    query: name,
                    fuzziness: 0,
                    boost: 10,
                  },
                },
              },
              {
                wildcard: {
                  name: {
                    value: `*${name}*`,
                  },
                },
              },
            ]
          },
        },
      },
    });
```

**Comment by nhtruong** [comment]
If I understand your ask correctly, you want to write a query that returns entries with either `donald's` or `donalds` specifically, or do you mean to ALWAYS ignore apostrophes in your search?

If it's specifically to `donald's`, you can use a `should` matcher, query_string, regex...
If it's for all generic words with apostrophes, you will likely need a [custom analyzer](https://opensearch.org/docs/latest/api-reference/analyze-apis/perform-text-analysis/#apply-a-custom-analyzer) with a `char_filter` that excludes apotrophes

**Comment by wbeckler** [comment]
@ahmadedris0 Does @nhtruong's answer make sense? I'll close this issue and you can reopen if there's more to it.
