### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-js#385]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by nhtruong** [comment]
The MAINTAINERS and CODEOWNERS lists look good to me.
@VachaShah would you mind taking a look at the permissions? Thank you!

**Comment by wbeckler** [comment]
@boktorbb and @mihirsoni are not showing up as maintainers on the repo permissions, nor as members of the opensearch project organization, and therefore adding them will be a few steps. It might make sense to confirm that they want to remain as maintainers before going through that process.

**Comment by kavilla** [comment]
> @boktorbb and @mihirsoni are not showing up as maintainers on the repo permissions, nor as members of the opensearch project organization, and therefore adding them will be a few steps. It might make sense to confirm that they want to remain as maintainers before going through that process.

I think they can go into emeritus per our guidelines. And they can re-ask for permissions in the future.

**Comment by wbeckler** [comment]
I agree with @kavilla's suggestion. It looks like neither of them have commits in the repo.

**Comment by dblock** [comment]
Verified, thanks.
