### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-js#390]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch-JS repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch-JS | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Link Checker, License, License Header, Changelog Verifier  | https://github.com/opensearch-project/opensearch-js/issues/390 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by nhtruong** [comment]
We have a [workflow that runs integration tests against old versions of OpenSearch](https://github.com/opensearch-project/opensearch-js/blob/main/.github/workflows/compatibility.yml). Do you think it satisfies that Backward Compatibility Tests requirement?

**Comment by scrawfor99** [comment]
Hi @nhtruong, that sounds like it would to me! I will update that. Sorry that I missed it before.

**Comment by VachaShah** [comment]
Closing this issue since all tests are present.
