### ISSUE TITLE
Cannot find module '@opensearch-project/opensearch/aws'

### ISSUE THREAD

**Issue by baolongt** [opensearch-project/opensearch-js#410]
https://github.com/opensearch-project/opensearch-js/blob/38217077918c56a28b001ce50464d9460e435877/USER_GUIDE.md?plain=1#L85
I follow the example in `USER_GUIDE.md` with Typescript SDK v3 

There is no error from ESLint but when I tried to test my code it raised an error 
> Cannot find module '@opensearch-project/opensearch/aws' from 'src/.../opensearch.ts'

I fix with importing the js file from the library's source code and it worked as I expected

```javascript
import { AwsSigv4Signer } from '@opensearch-project/opensearch/lib/aws/index';
```

Can it consider an issue or am I just testing wrong?
I use the Jest framework to write test

**Comment by dblock** [comment]
I am doing this in https://github.com/dblock/opensearch-node-client-demo/blob/afce84cda37df012b02cd2b66169719a069ef2d4/src/index.ts#L13 and that seems to work. Something else is amiss. Do you have a repro? Maybe add jest tests to my sample and see if the same problem occurs?

**Comment by baolongt** [comment]
Turnout this Jest bug not related to this library

Jest environment cannot import subpath `@opensearch-project/opensearch/aws` so what I did just add it to Jest config

`jest.config.js`

```javascript
 moduleNameMapper: {
    '@opensearch-project/opensearch/aws': '@opensearch-project/opensearch/lib/aws/index.js',
  }
```

**Comment by dblock** [comment]
Is there a bug opened in Jest @baolongt? Is that something we should do something about here?

**Comment by baolongt** [comment]
@dblock This is Jest's feature :D You can read more about this in this [link](https://github.com/facebook/jest/issues/12270).

**Comment by prudhvigodithi** [comment]
Using node version `v20.17.0` on amazon linux `6.1.109-118.189.amzn2023.x86_64`, I get the following errors:

Error when using `"@opensearch-project/opensearch": "^2.12.0",` and `import { AwsSigv4Signer } from '@opensearch-project/opensearch/aws-v3';`
```
/root/git/automation-app/src/utility/opensearch/opensearch-client.ts
  12:32  error  Unable to resolve path to module '@opensearch-project/opensearch/aws-v3'  import/no-unresolved
```

Same with `import { AwsSigv4Signer } from '@opensearch-project/opensearch/aws';`
```
  12:32  error  Unable to resolve path to module '@opensearch-project/opensearch/aws'  import/no-unresolved
  ```
  
  When used `import { AwsSigv4Signer } from '@opensearch-project/opensearch/lib/aws/index';`
  ```
  Error: Cannot find module '/root/git/automation-app/node_modules/@opensearch-project/opensearch/lib/aws/index'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1262:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1250:15)
    at resolveExports (node:internal/modules/cjs/loader:634:14)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/root/git/automation-app/bin/utility/opensearch/opensearch-client.js:14:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/root/git/automation-app/node_modules/@opensearch-project/opensearch/package.json'
  ```
  
  Just wanted to see if anyone still getting the same error?
  
  Thank you 
  @peterzhuamazon @getsaurabh02

**Comment by prudhvigodithi** [comment]
The above mentioned issue was fixed after adding `// eslint-disable-next-line import/no-unresolved` to the import `import { AwsSigv4Signer } from '@opensearch-project/opensearch/aws-v3';`, the error is thrown by `eslint`.
