### ISSUE TITLE
[BUG] Weird bug or Wrong error with client.search stress test

### ISSUE THREAD

**Issue by b5414** [opensearch-project/opensearch-js#415]
### What is the bug?
Calling:
`await client.search({index: 'opensearch_dashboards_sample_data_ecommerce',body: {...query},});`
with query:
`{"query": {"bool": {"must": [{"match": {"customer_full_name": "Oliver Rose"}}],"should": [{"match": {"day_of_week": "Thursday"}},{"match": {"day_of_week_i": 3}}],"minimum_should_match": 1,"must_not": [{"match": {"customer_last_name": "FEMALE"}}],"filter": {"range": {"taxful_total_price": {"gte": 30,"lte": 40}}}}}}`
sends an error `Unexpected token } in JSON at position 60` after ~19500 times

### Case description
In other words, I send 20000 requests with the same query with delay 10ms to 2 ECS tiny containers, the containers put the query in client.search func, and somewhere inside it an error occurs, which is returned to me as a response from the containers

### How can one reproduce the bug?
1. Have docker on amazon ECS
2. Add code from additional context (below)
3. Send ~20000 requests with 10ms delay

### What is the expected behavior?
I want to see either a normal error "you have exceeded _some_ limit", or to see the data; _Because I don't change anything in the request/query/code; I just sending 20000 completely identical requests and sometimes I meet this "wrong error"_

### What is your host/environment?
- It's Amazon ECS, so: Linux/X86_64
- With Docker container
- dockerfile `FROM node:18-alpine`

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?

```js
import {defaultProvider} from '@aws-sdk/credential-provider-node';
import {Client} from '@opensearch-project/opensearch';
import {AwsSigv4Signer} from '@opensearch-project/opensearch/aws';

const client = new Client({
	...AwsSigv4Signer({
		region: 'us-east-1',
		service: 'es',
		getCredentials: ()=>{
			const credentialsProvider = defaultProvider();
			return credentialsProvider();
		},
	}),
	node: '<private>',
});
```

```js
// [line2] err: "2 === Unexpected token } in JSON at position 60"
app.all('/line2', async(req, res, next)=>{
	try{
		const query = req.query;console.log('[line2] query:', JSON.stringify(query));

		try{
			// 2
			const response = await client.search({
				index: 'opensearch_dashboards_sample_data_ecommerce',
				body: {...query},
			});

			try{
				// 3
				res.send(JSON.stringify(response));
			}catch(e){throw new Error(`3 === ${e.message}`);}
		}catch(e){throw new Error(`2 === ${e.message}`);}
	}catch(e){console.log(`[line2] err: "${e.message}"`);next(e);}
});
```

```js
// [line2] err: "2 === 3 === Unexpected token } in JSON at position 60"
app.all('/line2', async(req, res, next)=>{
	try{
		const query = req.query;console.log('[line2] query:', JSON.stringify(query));

		try{
			// 2
			const preCalc = {
				index: 'opensearch_dashboards_sample_data_ecommerce',
				body: {...query},
			};

			try{
				// 3
				const response = await client.search(preCalc);

				res.send(JSON.stringify(response));
			}catch(e){throw new Error(`3 === ${e.message}`);}
		}catch(e){throw new Error(`2 === ${e.message}`);}
	}catch(e){console.log(`[line2] err: "${e.message}"`);next(e);}
});
```

**Comment by dblock** [comment]
I think some response is incorrectly parsed, help narrow it down? Log any error responses _before_ they are parsed to find out which one causes this, then we should be able to reproduce/write a unit test and fix.

**Comment by b5414** [comment]
@dblock how can I do it?

**Comment by dblock** [comment]
> @dblock how can I do it?

I haven't dug through the code deep enough, but maybe @nhtruong has some pointers?

**Comment by nhtruong** [comment]
@b5414 you can use callback to better inspect the error. For example:
```javascript
function myCallBack(err, result) {
  if (err) {
    // Insert Error handling here
  } else {
    return result;
  }
}

await client.search({<your query>}, {}, myCallBack)
```

**Comment by b5414** [comment]
_Unfortunately, we had to close this direction, opensearch does not have the functionality we need_ 🙃

Thus I won't be able to test the problem in my particular case, but the repeatability of this issue is ~90% and probably one of you will try your luck by running the code below 20000 times locally

```js
const query = {
	query: {
		bool: {
			must: [
				{
					match: {
						customer_full_name: 'Oliver Rose',
					},
				},
			],
			should: [
				{
					match: {
						day_of_week: 'Thursday',
					},
				},
				{
					match: {
						day_of_week_i: 3,
					},
				},
			],
			minimum_should_match: 1,
			must_not: [
				{
					match: {
						customer_last_name: 'FEMALE',
					},
				},
			],
			filter: {
				range: {
					taxful_total_price: {
						gte: 30,
						lte: 40,
					},
				},
			},
		},
	},
};

try{
	client.search({index: 'opensearch_dashboards_sample_data_ecommerce', body: {...query}}, {}, (e, result)=>{
		if(!e)return console.log('[test] result', result);

		console.log('[test] errMsg', e.message);
		console.log('[test] errJson', JSON.stringify(e));
		return false;
	});
}catch(e){
	console.log('[test] errCatch', e.message);
}
```

**Comment by dblock** [comment]
> _Unfortunately, we had to close this direction, opensearch does not have the functionality we need_ 🙃

Curious what was missing for your use case?
