### ISSUE TITLE
[BUG] [CCI] `SerializationError` class parameter `data` should be optional

### ISSUE THREAD

**Issue by timursaurus** [opensearch-project/opensearch-js#418]
### What is the bug?
In [lib/Serializer.js](https://github.com/opensearch-project/opensearch-js/blob/main/lib/Serializer.js#LL72C7-L72C76), the `ndserialize` static method of the `Serializer` class throws a `SerializationError` with a single `message` argument when the input data type is not an `Array`, although the `SerializationError` class requires [two arguments](https://github.com/opensearch-project/opensearch-js/blob/main/lib/errors.d.ts#LL71-L71C43).

### What is the expected behavior?
When the Array check fails, two required arguments should be passed to the SerializationError class

**Comment by timursaurus** [comment]
PR: https://github.com/opensearch-project/opensearch-js/pull/419

**Comment by timursaurus** [comment]
@nhtruong 
Or passing the `array` to [SerializationError](https://github.com/opensearch-project/opensearch-js/blob/main/lib/Serializer.js#LL72C7-L72C77)  would be better?

```js
if (Array.isArray(array) === false) {
      throw new SerializationError('The argument provided is not an array', array);
}
```

```diff
- throw new SerializationError('The argument provided is not an array');
+ throw new SerializationError('The argument provided is not an array', array);
```

**Comment by nhtruong** [comment]
Passing the data to the error constructor will give more context to the error so it's preferable. But I don't see the data being used in the Error class other than `this.data = data`

**Comment by timursaurus** [comment]
> Passing the data to the error constructor will give more context to the error so it's preferable. But I don't see the data being used in the Error class other than `this.data = data`

Right, changing the PR right now
