### ISSUE TITLE
[BUG] [CCI] DeprecationWarning: strictEqual() is deprecated, use equal() instead

### ISSUE THREAD

**Issue by ilikmeister** [opensearch-project/opensearch-js#434]
### What is the bug?
I experienced the following deprecation warning in ```bulk.test.js``` when I run yarn test
```
DeprecationWarning: strictEqual() is deprecated, use equal() instead
```

### How can one reproduce the bug?
```
yarn test
```

### What is the expected behavior?
To be fixed

### What is your host/environment?
Node v18

### Do you have any screenshots?
![image](https://user-images.githubusercontent.com/80389151/225301095-2852d5d7-b63b-47f8-b65a-f5c523330ab1.png)

### Do you have any additional context?
Replacing by equal() will remove the warning

**Comment by ilikmeister** [comment]
Addition to an issue:
Similar warning in ``bulk.test.js`` after yarn test:
``test/unit/helpers/bulk.test.js 2> (node:9860) DeprecationWarning: deepEqual() is deprecated, use same() instead``

**Comment by kavilla** [comment]
@ilikmeister thanks for opening!

Would you like to pick it up for a quick win?

**Comment by ilikmeister** [comment]
> @ilikmeister thanks for opening!
> 
> Would you like to pick it up for a quick win?

Sure, sir
