### ISSUE TITLE
[PROPOSAL] Update Developer Guide

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-js#435]
### What are you proposing?
 - Clean up the developer guide to be more illustrative to new contributors including how to install the library from scratch, e.g. "yarn install". 
 - Remove guidance on using `npm` and switch completely to yarn

**Comment by ilikmeister** [comment]
I found a possible error that Windows users might face during yarn installation, so may I add the steps for the solution in Developer_Guide.md?

**Comment by dblock** [comment]
> I found a possible error that Windows users might face during yarn installation, so may I add the steps for the solution in Developer_Guide.md?

Yes please.
