### ISSUE TITLE
[BUG] Feedback on Javascript client documentation

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/opensearch-js#437]
### What is the bug?
We received feedback on the Javascript documentation. Can you please review and help get it updated, as appropriate? 

### How can one reproduce the bug?

Comment 1: 
20230222 | /docs/latest/clients/javascript/index/ | wanted to check the updateByQueryMethod to see its example for TS/Javascript but couldn't find it

Comment 2: 
20230222  | /docs/latest/clients/javascript/helpers/  | where is the complete documentation for js?

### What is the expected behavior?
Here is the page in question: https://opensearch.org/docs/latest/clients/javascript/index/ and https://opensearch.org/docs/latest/clients/javascript/helpers/

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by kavilla** [comment]
Hello @hdhalter,

What would you need our help with? Would you like a list of APIs and params?

**Comment by wbeckler** [comment]
I think maybe we add links into the generated client documentation.

**Comment by nhtruong** [comment]
Here's the link to the generated API documentation: https://opensearch-project.github.io/opensearch-js/2.2/

**Comment by nhtruong** [comment]
UpdateByQuery can be found here: https://opensearch-project.github.io/opensearch-js/2.2/API-Document.html

**Comment by nhtruong** [comment]
We've added a series of Guides. This one has an example for update-by-query: https://github.com/opensearch-project/opensearch-js/blob/main/guides/document_lifecycle.md#update-multiple-documents-by-query
