### ISSUE TITLE
[PROPOSAL][CCI] Update a pull request template

### ISSUE THREAD

**Issue by Wielmany** [opensearch-project/opensearch-js#439]
### What are you proposing?
Updating/adding  a pull request template in this repository

### What problems are you trying to solve?
Currently, new contributors, when trying to propose a PR, are faced with a a pretty minimal pull request template (Describe what this change  achieves, what issue will be closed). 
While looking at other repos i noticed that they all have pull_request_templates in the ./github directory - but the main branch of this one doesn't (branches '1.x' and '1.1' do have it, for example). I'm not sure where's the current "default" PR request template is located/why is it like this - the above mentioned branches' templates have the checklist e.g. [1.x](https://github.com/opensearch-project/opensearch-js/blob/1.x/.github/PULL_REQUEST_TEMPLATE.md).

I propose to add a  PULL_REQUEST_TEMPLATE.md to the main branch with fuller template than the current one - by adding a check list to check for the PR submitter to check if commits are signed by DCO/ make sure that linter doesn't give errors/changelog is updated we can streamline pull request approval and integrate them faster because of that.

**Comment by Wielmany** [comment]
I would like to  add the PR template to the main branch (if i understood the issue correctly)

**Comment by VachaShah** [comment]
Hi @Wielmany, we use the [standardized template layout](https://github.com/opensearch-project/.github/blob/main/PULL_REQUEST_TEMPLATE.md) from [`.github`](https://github.com/opensearch-project/.github/) across all repos.

**Comment by Wielmany** [comment]
> Hi @Wielmany, we use the [standardized template layout](https://github.com/opensearch-project/.github/blob/main/PULL_REQUEST_TEMPLATE.md) from [`.github`](https://github.com/opensearch-project/.github/) across all repos.

Ah, thank you!
Some repos: [Opensearch Dashboard](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/pull_request_template.md) seem to use a custom templates(unless i'm missing something), i was thinking that custom template for our opensearch-js client would be quite useful, seeing how new contributors (especially those coming from CCI) might need a bit more guidance.
