### ISSUE TITLE
[PROPOSAL] [CCI] Update developer's guide regarding Windows script execution policy

### ISSUE THREAD

**Issue by Wielmany** [opensearch-project/opensearch-js#455]
### What are you proposing?
Currently the Developer's Guide solution to Windows not letting you running scripts on client PCs is to set the policy to Unrestricted. Running the yarn install script should be possible even with the execution policy set to ```RemoteSigned```, and this will also prevent users from opening themselves up to potential malicious unsigned scripts that they can run.
Alternatively, we could add the line about reverting the security policy back to restricted after installing `yarn` package.

**Comment by wbeckler** [comment]
Have you tested it?

**Comment by Wielmany** [comment]
I did test that yarn runs in RemoteSigned mode, yes
![Execution_policy](https://user-images.githubusercontent.com/89772209/227689093-4134391a-f1a3-4f1e-b1b5-b1896f3e72fe.png)
The tests also begin to run (not blocked by the RemoteSigned mode)
![image](https://user-images.githubusercontent.com/89772209/227689204-2ee0d1e0-4698-4521-bb9e-ed9e0401507d.png)
In contrast - if the execution police is undefined (in this case it's the same as Restricted) it's blocked 
![image](https://user-images.githubusercontent.com/89772209/227689261-b7efef37-4682-4ecf-a118-a00899f3acd2.png)

**Comment by ilikmeister** [comment]
Although, `unrestricted` will anyways warn the user when a script has been downloaded from the internet. So, in my book, there aren't any issues with it.

**Comment by Wielmany** [comment]
My concern was, how many people will read the warning instead of just clicking through (and since everything works fine with `remoteSigned` i think switching to it instead wouldn't hurt)

**Comment by ilikmeister** [comment]
Oh, that makes sense
