### ISSUE TITLE
[FEATURE] Feedback on Javascript documentation

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/opensearch-js#458]
### Is your feature request related to a problem?
We've gotten feedback on this topic: /docs/2.4/clients/javascript/index/

### What solution would you like?
Feedback was "Missing descriptions on how to use bulk indexing"

### What alternatives have you considered?
We got a similar request on /docs/latest/clients/java-rest-high-level/: "I am looking for bulk api"  

### Do you have any additional context?
Are there docs we can link to? Thanks.

_Add any other context or screenshots about the feature request here._

**Comment by hdhalter** [comment]
In your opinion, does the content in helpers.md address the user's concern for examples? The page they commented on (https://opensearch.org/docs/latest/clients/javascript/index/) does link to that helpers.md page. If the content is sufficient, maybe we can move the link to the page up to the top of the page so it's more findable?

**Comment by nhtruong** [comment]
I think it does address what the user is looking for. And I agree, visibility is the issue here. We should either mention that `bulk` in in the helper article or merge the helper article into the index one since it's not that big.

**Comment by hdhalter** [comment]
Ok, thanks for taking a look! I'll get this addressed and comment back in this issue once we've resolved it.

**Comment by nhtruong** [comment]
We've added a series of guides. This is is about Bulk: https://github.com/opensearch-project/opensearch-js/blob/main/guides/bulk.md
