### ISSUE TITLE
[Guide] Index Template

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-js#471]
Create `guides/index_template.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/index_template.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

**Comment by Nicksqain** [comment]
Hello! Can I take this issue?

**Comment by nhtruong** [comment]
@Nicksqain of course. Remember that you mainly only need to replace the ruby code-blocks with the JS code blocks. No need to rewrite the instructions in the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/index_template.md)

**Comment by Nicksqain** [comment]
> @Nicksqain of course. Remember that you mainly only need to replace the ruby code-blocks with the JS code blocks. No need to rewrite the instructions in the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/index_template.md)

Yes, thanks for the warning! That's exactly how I understood it!
