### ISSUE TITLE
[Guide] Search

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-js#473]
Create `guides/search.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/search.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

**Comment by sayuree** [comment]
Hi, I want to work on this issue

**Comment by nhtruong** [comment]
@sayuree go for it :)

**Comment by Nicksqain** [comment]
@nhtruong I already had a guide ready, can I do a PR? It's not very right of me, but I didn't work for nothing either :[

**Comment by sayuree** [comment]
@Nicksqain Well, I assume that according to the code of conduct, you are not allowed to work on already assigned issues. I admit that I did not submit the changes/commits right away, but still, it does not give an opportunity for others to take up the issue. There are still a bunch of issues you could work on, instead of attaching PR on already assigned ones. Please consider the code of conduct in the future.

**Comment by Nicksqain** [comment]
@nhtruong Yes, I apologize for my actions. It won't happen again. If suddenly the appointed person for some reason will not be able to work, then please accept my candidacy. I'm not trying to take away the time spent. It's just that I already did, but couldn't ask to be assigned to me. I apologize again.

**Comment by nhtruong** [comment]
@Nicksqain It's all good. I appreciate your candor and passion for this project. Since @sayuree has already been assigned to this issue, they have the priority on this issue. Feel free to pick up any other unclaimed issues and keep up the great work :D
