### ISSUE TITLE
[BUG] service parameter missing in AwsSigv4SignerOptions

### ISSUE THREAD

**Issue by nand-biz4group** [opensearch-project/opensearch-js#491]
![image](https://user-images.githubusercontent.com/91933621/231748273-65978f72-aa34-48d1-848d-d22fd5d92623.png)

interface AwsSigv4SignerOptions {
  getCredentials?: () => Promise<Credentials>;
  region: string;
  service?:string; 
}
Because it is required in opensearch serverless
![image](https://user-images.githubusercontent.com/91933621/231748473-9911dbe6-0e1f-442d-88b5-aaa002b65f0e.png)

**Comment by gauravbiz4group** [comment]
I think it's already resolved in GitHub repo code: 
![alreadyresolved](https://user-images.githubusercontent.com/104501273/232017046-f4aa17a4-a67c-407f-b858-1c7d38dca30d.png)
but not updated on the npm package:
![internalfile](https://user-images.githubusercontent.com/104501273/232017596-a1c87b20-5c92-4b53-a22b-824a12111179.png)

**Comment by dblock** [comment]
Fixed in https://github.com/opensearch-project/opensearch-js/pull/377 already. We need to release 2.3, add your +1 to https://github.com/opensearch-project/opensearch-js/issues/303 please.
