### ISSUE TITLE
Bulk analyze

### ISSUE THREAD

**Issue by Jasenpan1987** [opensearch-project/opensearch-js#534]
Hi,

Is there a way I can perform a bulk analyze in opensearch? I need to analyze a number of texts and get back the analyzed result.

Thanks in advance.

**Comment by nhtruong** [comment]
I'm afraid we don't have that feature yet. Right now you can only do bulk Index/create/update/delete on the docs. You can request this feature on https://github.com/opensearch-project/OpenSearch
