### ISSUE TITLE
[BUG] ERR_PACKAGE_PATH_NOT_EXPORTED issue encountered when upgrading to NodeJS 18 runtime

### ISSUE THREAD

**Issue by rayhive** [opensearch-project/opensearch-js#560]
### What is the bug?
We've had the "@opensearch-project/opensearch" working in an app running against the Node JS 14 runtime. Howerver we've recently tried upgrading our app's runtime to NodeJS 18 and experience the issue below. 

`ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Package subpath './lib/errors' is not defined by \"exports\" in /var/task/node_modules/@opensearch-project/opensearch/package.json","code":"ERR_PACKAGE_PATH_NOT_EXPORTED","stack":["Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/errors' is not defined by \"exports\" in /var/task/node_modules/@opensearch-project/opensearch/package.json","    at new NodeError (node:internal/errors:399:5)`

### How can one reproduce the bug?
Import a module like: import { ResponseError } from '@opensearch-project/opensearch/lib/errors';

### What is the expected behavior?
module imports without errors

### What is your host/environment?

- NodeJS 18.16.1, 
- @opensearch-project/opensearch": "2.1.0". Also tried it on versions "2.3.0", "2.2.1", "1.2.0"

**Comment by nhtruong** [comment]
@rayhive thanks for bringing this to our attention. Do you encounter this in other versions of Node as well? Esp the newer ones?

**Comment by rayhive** [comment]
Hi @nhtruong, thanks for your response. We encountered this issue with the NodeJS 16, as well as 18 runtimes.  Ideally we're looking to upgrade our runtime from version 14 to version 18.

**Comment by mahajanvivektech** [comment]
Is there an ETA as it's a kind of a blocker for us ?
@nhtruong

**Comment by nhtruong** [comment]
@mahajanvivektech Our [integration](https://github.com/opensearch-project/opensearch-js/blob/main/.github/workflows/integration.yml#L20) and [unit](https://github.com/opensearch-project/opensearch-js/blob/main/.github/workflows/nodejs.yml#L21) tests do include 18.x and they don't encounter this error. Lemme see if I can recreate this.

**Comment by nhtruong** [comment]
Is this what you're looking for?
```
import { errors } from '@opensearch-project/opensearch';

console.log(errors.ResponseError)
```

**Comment by mahajanvivektech** [comment]
@nhtruong , this is what we are looking out for us to work.
Even in our case it works at the unit test level level. However, when we try running it at runtime either through Lambda or locally, we get the error.

**Comment by mahajanvivektech** [comment]
Hi @nhtruong ,

Yeah, Thanks for sharing: https://github.com/opensearch-project/opensearch-js/blob/b892c6954731f98f76bd464cef9d320ca0763f50/lib/errors.d.ts#L87

We will give it a shot and let you know if it works

**Comment by rayhive** [comment]
> Is this what you're looking for?
> 
> ```
> import { errors } from '@opensearch-project/opensearch';
> 
> console.log(errors.ResponseError)
> ```

Thanks for that @nhtruong, that's resolved the issue running this locally on my workstation - also, I upgraded to  @opensearch-project/opensearch 2.3.1. We'll give this a test in the office, otherwise looking good, cheers.

**Comment by nhtruong** [comment]
Glad that was resolved. I'm going to close this ticket then.
