### ISSUE TITLE
[BUG] OpenSearh buffer.constants is undefined error in my VUEJS Project

### ISSUE THREAD

**Issue by zeynep-turker** [opensearch-project/opensearch-js#582]
Hi, everyone. When I try to use opensearch library in my VueJS Project, I got a problem.

Firstly, I installed npm install @opensearch-project/opensearch. When I build, I got V8 error below.

`This dependency was not found:
v8 in ./node_modules/@opensearch-project/opensearch/lib/Transport.js
To install it, you can run: npm install --save v8
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
PS C:\Users\tt\Desktop\repo\TMS\tms-web-ui> npm install --save v8`

End then, I installed "npm install --save v8". After the installing, my project was successfully build but when I run serve, my browser said buffer.constants are undefined. Error is below.

`Uncaught TypeError: buffer.constants is undefined
    <anonymous> webpack-internal:///./node_modules/@opensearch-project/opensearch/lib/Transport.js:53
    <anonymous> webpack-internal:///./node_modules/@opensearch-project/opensearch/lib/Transport.js:734
    node_modules opensearch-project/opensearch/lib/Transport.js@http://localhost:8080/js/chunk-vendors.js:719
    __webpack_require__ http://localhost:8080/js/app.js:849
    fn http://localhost:8080/js/app.js:151
    <anonymous> webpack-internal:///./node_modules/@opensearch-project/opensearch/index.js:35
    <anonymous> webpack-internal:///./node_modules/@opensearch-project/opensearch/index.js:354
    node_modules opensearch-project/opensearch/index.js@http://localhost:8080/js/chunk-vendors.js:671
    __webpack_require__ http://localhost:8080/js/app.js:849
    fn http://localhost:8080/js/app.js:151
    <anonymous> webpack-internal:///./src/tms/open_search_api.js:2
    js http://localhost:8080/js/app.js:2169
    __webpack_require__ http://localhost:8080/js/app.js:849
    fn http://localhost:8080/js/app.js:151
    <anonymous> webpack-internal:///./src/tms/index.js:9
    js http://localhost:8080/js/app.js:2145
    __webpack_require__ http://localhost:8080/js/app.js:849
    fn http://localhost:8080/js/app.js:151
    <anonymous> webpack-internal:///./src/main.js:8
    js http://localhost:8080/js/app.js:2073
    __webpack_require__ http://localhost:8080/js/app.js:849
    fn http://localhost:8080/js/app.js:151
    1 http://localhost:8080/js/app.js:2470
    __webpack_require__ http://localhost:8080/js/app.js:849
    checkDeferredModules http://localhost:8080/js/app.js:46
    <anonymous> http://localhost:8080/js/app.js:925
    <anonymous> http://localhost:8080/js/app.js:928`

I must to use opensearch library in my project. Can you help me to fix this problem?

**Comment by wbeckler** [comment]
Can you explain your overall architecture a little? The client is a node.js client and isn't designed to talk to an OpenSearch cluster directly from a browser. Usually you proxy browser requests through a web server.

**Comment by zeynep-turker** [comment]
I am trying to send request directly from my UI which works on VueJS environment. I did not use any proxy to redirect my requests.

**Comment by nhtruong** [comment]
@zeynep-turker I don't think this is an issue specific to OpenSearch. Have you tried solutions proposed one [StackOverflow](https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined)?

**Comment by zeynep-turker** [comment]
When I created the project again, the problem was solved interestingly. Before that, I remember trying [the solution ](https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined) on StackOverflow, but it did not work. Thanks anyway.

**Comment by zeynep-turker** [comment]
We used the node.js project to use OpenSearch. Before this, I remember trying [the solution](https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined) on StackOverflow but it didn't work. Thanks anyway.
