### ISSUE TITLE
[FEATURE] Add support to check if the index exists?

### ISSUE THREAD

**Issue by akshay-vishnoi** [opensearch-project/opensearch-js#597]
### Is your feature request related to a problem?
OpenSearch gives an option to check if the [index exists](https://opensearch.org/docs/latest/api-reference/index-apis/exists/) by simply returning the status of either 200 or 404. But this package doesn't support this API yet.

### What alternatives have you considered?
For now, I have to run the operation like deleting the index and catching the error index-not-found. 

Or please let me know if the support already exists. Thanks

**Comment by nhtruong** [comment]
It does actually: https://github.com/opensearch-project/opensearch-js/blob/4031f96f06225383c33e0c58c5455bd6c1dae95c/api/api/indices.js#L667
`client.indices.exists({ index: 'books'})`
API actions related to manipulating indices can be found in the `indices` namespace
