### ISSUE TITLE
[FEATURE] Make raw JSON REST requests to OpenSearch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-js#631]
### Is your feature request related to a problem?

Coming from https://github.com/opensearch-project/opensearch-clients/issues/62, add support for making raw JSON requests.

### What solution would you like?

1. Document `transport.request`, similar to https://github.com/opensearch-project/opensearch-py/pull/542. See https://github.com/opensearch-project/opensearch-js/issues/264#issuecomment-1192823105 for an example.
2. Add a high level DSL, e.g. `client.get` and `client.post`.

**Comment by AbhinavGarg90** [comment]
I'd love to pick this issue up if it is available @dblock.

**Comment by dblock** [comment]
All yours @AbhinavGarg90
