### ISSUE TITLE
[BUG] deprecation warnings are missing from `.d.ts` files

### ISSUE THREAD

**Issue by alex-at-cascade** [opensearch-project/opensearch-js#637]
### What is the bug?
In `index.d.ts`, there is no deprecation warning on `putTemplate`, even though the javascript source *does* have one.  Based on the lack of warning, I used this function, resulting in an unfortunate outcome.

### How can one reproduce the bug?
In an IDE, autocomplete from `client.indices.` and see `putTemplate` come up.

### What is the expected behavior?
Deprecation warnings would be carried to the `.d.ts` declarations.  (Would be even better if *all* the jsdoc was carried over.)

### What is your host/environment?
N/A

### Do you have any screenshots?
N/A

### Do you have any additional context?
N/A

**Comment by nhtruong** [comment]
Thanks for bringing it up #645 will take care of this :)
