### ISSUE TITLE
[BUG] Module not found: Opensearch Errors 

### ISSUE THREAD

**Issue by azwraithnp** [opensearch-project/opensearch-js#651]
### What is the bug?

I'm currently utilizing some types from @opensearch-project/opensearch/lib/errors namely 
-  ConnectionError,
-   NoLivingConnectionsError,
-   RequestAbortedError,
-   ResponseError,

Running the code via Docker results in not being able to find the module. This is on NestJS. Didnt' face this issue before until the node version upgrade. 

### How can one reproduce the bug?
Importing a type from @opensearch-project/opensearch/lib/errors in the mentioned node version

### What is your host/environment?
@types/node: ^20.0.0 from ^16.0.0
node:alpine3.17
Dockerfile

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-js/assets/14939765/fac9f352-bfb7-4dcd-81dc-521215596b89)
![image](https://github.com/opensearch-project/opensearch-js/assets/14939765/ee038fc0-ff76-42f6-a81e-d772399237bb)

**Comment by khaizaki-accesstel** [comment]
Facing the same issue upgrading node (from v16 to v18).

I managed to get the import working as such:

```js
// import { ResponseError } from '@opensearch-project/opensearch/lib/errors';
import { errors } from '@opensearch-project/opensearch';

// access the class via the `errors`
errors.ResponseError
```

**Comment by azwraithnp** [comment]
> Facing the same issue upgrading node (from v16 to v18).
> 
> I managed to get the import working as such:
> 
> ```js
> // import { ResponseError } from '@opensearch-project/opensearch/lib/errors';
> import { errors } from '@opensearch-project/opensearch';
> 
> // access the class via the `errors`
> errors.ResponseError
> ```

Thanks for the update, I fixed it in the same way. I believe, for now, this should be the way to go. Closing the issue.
