### ISSUE TITLE
[BUG] Documented Parameter for Delete-Index API Call is Unsupported

### ISSUE THREAD

**Issue by jasel-lewis** [opensearch-project/opensearch-js#658]
### What is the bug?
Within the Index Lifecycle guide, [the "Delete an Index" example](https://github.com/opensearch-project/opensearch-js/blob/2.4/guides/index_lifecycle.md#delete-an-index), demonstrates that an `ignore: 404` parameter should be passed in order to prevent an error from being returned if one or more indices do not exist.

When using this parameter, however, an error is thrown with the message: `request [/{index-name-here}] contains unrecognized parameter: [ignore]` (where `{index-name-here}` is the name of the index that was identified for deletion. A similar error occurs if you pass an array (as in the example) of index names.

In looking at [the code for the delete-index method](https://github.com/opensearch-project/opensearch-js/blob/2.4/api/api/indices.js) (line 444 begins the method definition), there indeed seems to be no such parameter accepted. There is, however, a Boolean `ignore_unavailable` parameter which seems to do the job.

### How can one reproduce the bug?
Call the delete-index API method, passing the name of an index that does not exist and passing `ignore: 404` as in the Index Lifecycle example.

### What is the expected behavior?
According to the Index Lifecycle guide, no error should be thrown.

### What is your host/environment?
Host environment is an AWS Lambda function, so some version of Linux running our Node.js lambda (which exercises the `@opensearch-project/opensearch` API.

### Proposed Resolution
I don't quite care which approach is taken, but one of the following should be taken with preference given to whichever best aligns with the mission and/or future direction of this project.

1. Update the _documentation_ to reflect the correct parameter to pass that will cause the index-delete API call to _not_ throw an error when an index does not exist.
2. Update the _code_ (the `IndicesApi.prototype.delete`  function) to operate as the documentation prescribes.

**Comment by dblock** [comment]
Needs some digging on which parameter is correct, probably a mistake in the guide. Want to help fix this @jasel-lewis? I would add a working sample to https://github.com/opensearch-project/opensearch-js/tree/main/samples extracted from that guide, and fix the guide.

**Comment by jasel-lewis** [comment]
@dblock When I can find the time, I'd love to.

**Comment by tejeshreddy** [comment]
@nhtruong can I take a look at this issue?

**Comment by nhtruong** [comment]
@tejeshreddy of course. Feel free to pick up any issues you want. Just left a comment so others know. And thank you :)

**Comment by nhtruong** [comment]
@jasel-lewis The JS client doesn't have this feature. The guide was copy-pasted from the Ruby Client which does support this.

@tejeshreddy You can update the guide accordingly to remove this. We can raise this as a feature request.

**Comment by tejeshreddy** [comment]
@jasel-lewis - there's another parameter that is responsible for ignoring errors while deleting indices that do not exist. Please refer below - 
```javascript
await client.indices.delete({
    index: ['movies', 'paintings', 'burner'],
    ignore_unavailable: true,
  });
```
Also, sorry for the misinformation in the guide. The upcoming PR should fix it.

@nhtruong - The guide currently mentions about a [parameter](https://github.com/opensearch-project/opensearch-js/blob/2.4/guides/index_lifecycle.md#delete-an-index) called `ignore`. Should we have to honor this parameter? If so, it would require code changes else updating the guide would do.

**Comment by nhtruong** [comment]
Doc fixed by https://github.com/opensearch-project/opensearch-js/pull/665 with the correct param
