### ISSUE TITLE
[FEATURE] Search Pipelines in opensearch-js

### ISSUE THREAD

**Issue by sejli** [opensearch-project/opensearch-js#679]
### Is your feature request related to a problem?
The [search pipelines](https://opensearch.org/docs/latest/search-plugins/search-pipelines/index/) feature was released officially in `2.9`.  Example search with a pipeline:
```
POST /opensearch_sample_data_flights/_search?search_pipeline=my_pipeline
{
   "query": {
      "match_all:" {}
   }
}
```

The `request` in `opensearch-js` currently does not have a parameter for a search_pipeline.

### What solution would you like?
Add a parameter for `search_pipeline` for search requests.

### What alternatives have you considered?
Currently, adding a `search_pipeline` parameter [works](https://github.com/opensearch-project/dashboards-search-relevance/pull/352/files#diff-1574d6b9f1bcbb4074dc3f87a7a25eda1d8606869f0fe6acd7f75b6ecdb92b05R42), but it is not declared in `opensearch-js`, and the linter throws errors.

### Do you have any additional context?
N/A

**Comment by nhtruong** [comment]
Thanks @sejli 
I've raised an issue in the [API Spec](https://github.com/opensearch-project/opensearch-api-specification/issues/171) repo as eventually this will be handled by a client generator that will read the spec and generate the API code. We're currently working on the generator ourselves.

In the meantime, feel free to raise a PR to update the input type for the `search` operation if no one has gotten to it. If you have any questions, don't hesitate to ask :)

**Comment by sumukhswamy** [comment]
@nhtruong any update on this? The PR was closed recently.

**Comment by nhtruong** [comment]
It was probably closed by mistake. Just restored it. Lemme rebase it and get it merged.
