### ISSUE TITLE
[BUG] index_not_found_exception is thrown intermittently

### ISSUE THREAD

**Issue by Abhisha1** [opensearch-project/opensearch-js#687]
### What is the bug?
I am working with Amazon OpenSearch Serverless and have noticed the index_not_found_exception getting thrown when I try to create and index intermittently, and sometimes when I try a bulk operation.

### How can one reproduce the bug?
The error pops up somewhat randomly but here are the two scenarios I've seen the bug

1. Check if index exists
2. Create index (it can fail here)
3. Create a bulk operation which inserts data (it can fail here)

### What is the expected behavior?
The index should be created or the data inserted

### What is your host/environment?
OpenSearch Serverless

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-js/assets/35671786/0970397b-5acd-41c4-b07f-745f4d06461d)
![image](https://github.com/opensearch-project/opensearch-js/assets/35671786/05d13874-e92f-40d6-b7ae-77212a5966f8)
![image](https://github.com/opensearch-project/opensearch-js/assets/35671786/f6b24956-2b54-48dd-a81e-10a0bd0b0e32)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
@Abhisha1 This looks like a problem with serverless specifically, have you opened a support ticket with AWS yet?

**Comment by Abhisha1** [comment]
Ahh I see, wasn't sure what the best place was. I will raise a support ticket there in that case. Thanks @dblock

**Comment by sricharanvuppu** [comment]
@Abhisha1 , It looks like you are using Index UUID to check if index exists, did you try with Index name ?
