### ISSUE TITLE
[BUG] Not able to search for texts with space and dash in between.

### ISSUE THREAD

**Issue by aniruddha-mahamuni-bh** [opensearch-project/opensearch-js#692]
### What is the bug?
I am using Javascript client https://opensearch.org/docs/latest/clients/javascript/index/ to fetch data from opensearch. I am using the below query to fetch data 
```
{
  "track_total_hits": true,
  "from": 0,
  "size": 100,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "name": "*test *"
          }
        },
        {
          "wildcard": {
            "description": "*test *"
          }
        }
      ]
    }
  },
  "_source": ["name", "description"], 
  "track_scores": true
}
```
In our data set we have name and description as "test data" for few records. So, in the query if we give input as test with space (**test** ) it is not returning the data set with name as "test data" or "test-data". The same scenario if for dash in between the text
In our data set we have name and description as "test-data" for few records. So, in the query if we give input as test with a hyphen/dash (**test-**) it is not returning the data set with name/description as "test-data".

Check below image for response
![image](https://github.com/opensearch-project/opensearch-js/assets/88440456/46fc0459-c3d5-4b86-8f6a-2833eecfd45c)

### How can one reproduce the bug?
To reproduce the bug you can use the above query for testing the spaces issue.
For testing the hyphen/dash issue you can refer the below query
```
{
  "track_total_hits": true,
  "from": 0,
  "size": 100,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "name": "*test-*"
          }
        },
        {
          "wildcard": {
            "description": "*test-*"
          }
        }
      ]
    }
  },
  "_source": ["name", "description"], 
  "track_scores": true
}
```

### What is the expected behavior?
It should return data for text with spaces and hyphen/dash.

### What is your host/environment?
_Operating system - Linux, 
opensearch version - https://opensearch.org/docs/2.11/about/._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
Is the query the problem or the client? Meaning can this be reproduced with `curl`?

**Comment by aniruddha-mahamuni-bh** [comment]
Yes it can be reproduced using curl also.
 This is now fixed. We fixed this by adding params in index mappings
 We have added in the properties section of name, description.
``` 
"analyzer": "keyword_lowercase",
"fielddata": true
```
