### ISSUE TITLE
[Release] Release 2.6.0 version of opensearch-js client with some security fixes and feature enhancement

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/opensearch-js#729]
## Is your feature request related to a problem? Please describe

We have total [26 commits](https://github.com/opensearch-project/opensearch-js/compare/2.5.0...main) in the [main](https://github.com/opensearch-project/opensearch-js) branch after [2.5.0 release](https://github.com/opensearch-project/opensearch-js/tree/2.5.0). This includes version bump for many libraries and some important feature enhancements.

- #725 
- #584 
- #723 
- #707 
- #708 

## Describe the solution you'd like
Release opensearch-js 2.6.0 and publish to [NPM](https://www.npmjs.com/package/@opensearch-project/opensearch).

**Comment by nhtruong** [comment]
2.6.0 Client has been released!
