### ISSUE TITLE
Can somebody help, using openSearch directly from client like ReactJS, NextJS is good idea or it should communicate with backend only

### ISSUE THREAD

**Issue by bharat5604** [opensearch-project/opensearch-js#736]

**Comment by wbeckler** [comment]
Can you please edit your issue to include more context on your goals and options you've considered?

**Comment by bharat5604** [comment]
Hi @wbeckler , my question is what is the OpenSearch best practices: use directly from the frontend or from the backend

**Comment by wbeckler** [comment]
Because you need to authenticate requests and directly manage the format and frequency of requests, it's rare that someone connects browser to database. The opensearch-dashboards application has the typical architecture: database <-> node server <-> browser

**Comment by dblock** [comment]
I'll close this isssue, @bharat5604 a good place to ask general questions is https://opensearch.org/slack.html.
