### ISSUE TITLE
[FEATURE] plans to support rollup & transform APIs?

### ISSUE THREAD

**Issue by djmadeira** [opensearch-project/opensearch-js#744]
### Is your feature request related to a problem?
JS client does not support rollup and transform features of OS

### What solution would you like?
Add support to programmatically control rollup and transform features

**Comment by dblock** [comment]
Yes, please contribute specs to https://github.com/opensearch-project/opensearch-api-specification (mind https://github.com/opensearch-project/opensearch-api-specification/pull/208 that is switching to OpenAPI), the clients are generated from there.

**Comment by djmadeira** [comment]
Trying to get these specs typed up, @dblock can you point me to the source code where rollups are implemented? The [docs page](https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#get-an-index-rollup-job) isn't nearly complete enough for me to work out what all the possible values are.

**Comment by dblock** [comment]
I think it's [in ISM](https://github.com/search?q=repo%3Aopensearch-project%2Findex-management%20_rollup&type=code)

**Comment by djmadeira** [comment]
Added specs for [rollups](https://github.com/opensearch-project/opensearch-api-specification/pull/283) and [transforms](https://github.com/opensearch-project/opensearch-api-specification/pull/288)

**Comment by nhtruong** [comment]
The generator for this client is still its infancy but I can try and generate some of it and edit it manually

**Comment by djmadeira** [comment]
@nhtruong any idea when we can expect these? Is this a relatively simple change?

**Comment by nhtruong** [comment]
I'm aiming to have these merged and deployed by the end of the week.
I can generate these methods now. Need to iron out the edge cases and then manually insert these methods into the API.
Will keep you posted on the progress through out the week.

**Comment by nhtruong** [comment]
Here's the [draft](https://github.com/opensearch-project/opensearch-js/pull/797). Please take a look.
Still need to add some basic typing so the IDEs can autocomplete for these added functions.

**Comment by nhtruong** [comment]
@djmadeira [PR](https://github.com/opensearch-project/opensearch-js/pull/797) is ready for review

**Comment by nhtruong** [comment]
It will be part of 2.10.0 that will be released later today: https://github.com/opensearch-project/opensearch-js/pull/798

**Comment by nhtruong** [comment]
[2.10.0](https://www.npmjs.com/package/@opensearch-project/opensearch/v/2.10.0) has been published
