### ISSUE TITLE
[BUG] AWS SIGv4 signer does not fully implement TransportRequestPromise

### ISSUE THREAD

**Issue by u873838** [opensearch-project/opensearch-js#819]
### What is the bug?

The `AwsSigv4SignerTransport.request`  method does not return a Promise that implements all of the TransportRequestPromise members.

https://github.com/opensearch-project/opensearch-js/blob/27c464faeb791fcc6aa1a17d73567212fbdd1432/lib/Transport.d.ts#L150-L153

https://github.com/opensearch-project/opensearch-js/blob/27c464faeb791fcc6aa1a17d73567212fbdd1432/lib/aws/shared.js#L80-L81

### How can one reproduce the bug?

Create a new Client that uses the AWS SIGV4 signer.
Then attempting to call `.abort()` on the returned Promise of any of the client API methods will result in a TypeError being thrown.

### What is the expected behavior?

The method should exist on the Promise returned by the Transport; in-flight requests that are SIGV4 signed should be abortable.

### Do you have any additional context?

The 3.X fix is to accept an AbortSignal parameter on API methods which will allow in-flight requests to be cancelled.

**Comment by dblock** [comment]
Does this need to wait for 3.0? Care to contribute to the current version?
