### ISSUE TITLE
[BUG] Opensearch x.0.0 beta should not be set as latest in npm 

### ISSUE THREAD

**Issue by JaredAAT** [opensearch-project/opensearch-js#849]
### What is the bug?
Opensearch version 3.0.0 beta x is showing up as the latest build in npm:

![image](https://github.com/user-attachments/assets/381b85ef-6c8a-406e-b1f3-55304fd65cbd)

You probably want to set beta against anything that is... well a beta: https://egghead.io/lessons/javascript-publishing-a-beta-version

**Comment by nhtruong** [comment]
Thank you for bringing this to our attention.

@gaiksaya, is there a way to trigger our release pipeline for a beta release on npm? (i.e.  using `npm publish --tag beta`)

**Comment by gaiksaya** [comment]
We have a similar issue here: https://github.com/opensearch-project/opensearch-build-libraries/issues/206
Will see if I can work on it. 
Thanks!

**Comment by dblock** [comment]
I believe this was resolved @gaiksaya @nhtruong? Close?

**Comment by gaiksaya** [comment]
The PR is yet to be merged and later upgrade the versions in these jenkinsFiles. https://github.com/opensearch-project/opensearch-build-libraries/pull/492
Will try to get in soon. Sorry about the delay.
