### ISSUE TITLE
[BUG] <title> SortCombinations typings lacking interfaces/types

### ISSUE THREAD

**Issue by logan858** [opensearch-project/opensearch-js#850]
### Describe the bug

I have a project where I'm converting from elasticsearch to opensearch, on a node/express server. (npm v  @opensearch-project/opensearch@3.0.0-beta.3 )

I am noticing some (potential?) issues with the typings in this package, specifically the sort: 
![image](https://github.com/user-attachments/assets/714db097-9db5-4567-a525-6ebcd7c1c67d)
sortQuery:
![image](https://github.com/user-attachments/assets/188b189b-49bc-4ffd-9b5b-ef18532dac0d)
![image](https://github.com/user-attachments/assets/eec4bfad-93de-4f67-a3fb-3c40cb7db025)

my sortQuery func needs to return a SortCombinations compliant type object.  In elasticsearch, the SortCombinations accomodates sorting by the field name with the SortOptions type like so:
es typings:
![image](https://github.com/user-attachments/assets/b02135b1-0522-4996-92a9-1467235a1e5c)

BUT, when we see the similar sort typings in os, it lacks the SortOptions of [property: string]: FieldSort | SortOrder | etc, etc. which allows the correct typings to be recognized for sorting by field names.  
![image](https://github.com/user-attachments/assets/e552a2ea-f483-4a91-9026-25163f011385)

When using my own 'incorrectly' typed code it works perfectly fine to sort the opensearch results despite what the typings show , and in the opensearch docs it shows the functionality as one would expect:
![image](https://github.com/user-attachments/assets/63655e6b-30d8-4334-bb81-e7d3a8262071)

### Related component

Search

### To Reproduce

1. Build an opensearch search query in ts/js.
2. and a sort object to the body
3. see typings mismatch

### Expected behavior

typings should include field name sorting.

**Comment by nhtruong** [comment]
Thank you for bringing this to our attention. This incomplete typing for sort comes from the [spec](https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/schemas/_common.yaml#L454-L476), which 3.x API is generated from. I've created an [issue](https://github.com/opensearch-project/opensearch-api-specification/issues/529) for it.

**Comment by nhtruong** [comment]
Closing as the spec has been [updated](https://github.com/opensearch-project/opensearch-api-specification/pull/563) and we're releasing beta.7 that includes the [change](https://github.com/opensearch-project/opensearch-js/pull/869/files#diff-c788452b086b7ead7ff60c9858adcf2706c7d694c2551e4ca4b324b9c4f1551cL731).
