### ISSUE TITLE
[BUG] NPE on bulk upsert request

### ISSUE THREAD

**Issue by vladru** [opensearch-project/opensearch-js#890]
### What is the bug?
Bulk upsert request fails with HTTP status code 500 and  null pointer exception with reason
"Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null"

### How can one reproduce the bug?
Use simplest bulk upsert request, for an example from the [API documentation](https://opensearch.org/docs/latest/api-reference/document-apis/bulk/#upsert):
```
POST _bulk
{ "update": { "_index": "movies", "_id": "tt0816711" } }
{ "doc" : { "title": "World War Z" }, "doc_as_upsert": true }
```
The request fail as described above.
I've tried send such request using javascript client (v.2.12.0) and also from DevTools in OpenSearch Dshboard - responses are the same

### What is the expected behavior?
Request inserts new record to the index.

### What is your host/environment?
Client side Windows 11 Enterprise
Domain cluster OpenSearch 2.15 (latest)

### Do you have any screenshots?
No

### Do you have any additional context?
No

**Comment by vladru** [comment]
I think it was mustake create bug report in this project, so I've created new one in
https://github.com/opensearch-project/OpenSearch/issues/16524

**Comment by dblock** [comment]
Thanks, let's close this one here.
