### ISSUE TITLE
No typings on search body, other than Record<string, any>

### ISSUE THREAD

**Issue by paul-uz** [opensearch-project/opensearch-js#942]
Is there a way to get better typings on the body of a search result for example?

```
  search<
    TResponse = Record<string, any>,
    TRequestBody extends RequestBody = Record<string, any>,
    TContext = Context
  >(
    params?: RequestParams.Search<TRequestBody>,
    options?: TransportRequestOptions
  ): TransportRequestPromise<ApiResponse<TResponse, TContext>>;
```

I see there is `SearchResponse` for Msearch, but not Search

**Comment by nhtruong** [comment]
@paul-uz which version of the client are you using? We're testing Version 3.0.0 with [beta-8](https://www.npmjs.com/package/@opensearch-project/opensearch/v/3.0.0-beta.8) already out that have all request and response types.

**Comment by paul-uz** [comment]
Just using the latest stable release, set as ^2.13.0 in our package file. When will V3 be released officially?

**Comment by paul-uz** [comment]
I just installed beta-8, and whilst i can click through and find the new type ie

```
export type Search_Response = ApiResponse & {
  body: Search_ResponseBody;
}
```

`body` is just showing as `any` in my IDE, VSCode :/

**Comment by paul-uz** [comment]
VSCode intellisense gives me this typing

```
const response: {
    body: any;
    statusCode: number | null;
    headers: Record<string, any> | null;
    warnings: string[] | null;
    meta: {
        context: unknown;
        name: string | symbol;
        request: {
            params: TransportRequestParams;
            options: TransportRequestOptions;
            id: any;
        };
        connection: Connection;
        attempts: number;
        aborted: boolean;
        sniff?: {
            hosts: any[];
            reason: string;
        } | undefined;
    };
    body: ResponseBody;
}
```

`body` is deifned twice somehow

**Comment by nhtruong** [comment]
The typing in this [comment](https://github.com/opensearch-project/opensearch-js/issues/942#issuecomment-2547150756) is coming from the 2.x version. Make sure that the 2.x package has been removed from your env.

**Comment by paul-uz** [comment]
> The typing in this [comment](https://github.com/opensearch-project/opensearch-js/issues/942#issuecomment-2547150756) is coming from the 2.x version. Make sure that the 2.x package has been removed from your env.

I simply installed the beta over the top via NPM.

I'll try removing node_modules and reinstalling.

**Comment by paul-uz** [comment]
Code from 3.0.0-beta.8

```
export type Search_Response = ApiResponse & {
  body: Search_ResponseBody;
}
```

```
export interface ApiResponse {
  body: any;
  statusCode: number | null;
  headers: Record<string, any> | null;
  warnings: string[] | null;
  meta: {
    context: unknown;
    name: string | symbol;
    request: {
      params: TransportRequestParams;
      options: TransportRequestOptions;
      id: any;
    };
    connection: Connection;
    attempts: number;
    aborted: boolean;
    sniff?: {
      hosts: any[];
      reason: string;
    };
  };
}
```

**Comment by paul-uz** [comment]
Beta 7

```
export interface Search_Response extends ApiResponse {
  body: Search_ResponseBody;
}
```

there's the bug ;)

**Comment by nhtruong** [comment]
That's super odd. I'll look into it. Thanks for the finding.

**Comment by paul-uz** [comment]
> That's super odd. I'll look into it. Thanks for the finding.

Yea looks like the change to a type union broke it. Happy to PR to revert if there is a workflow for contributions to V3?

**Comment by nhtruong** [comment]
Thanks @paul-uz The fix is gonna be a bit more involved than that because that file was generated from the spec. I'm going to update the generator.

**Comment by paul-uz** [comment]
I'll leave it in your capable hands haha.

**Comment by nhtruong** [comment]
@paul-uz [beta-9](https://www.npmjs.com/package/@opensearch-project/opensearch/v/3.0.0-beta.9) is out with the fix.
